### ISSUE TITLE
Is this the correct wordlist?

### ISSUE THREAD

**Issue by DavidMertz** [LaurentLessard/wordlesolver#3]
The repo uses a "5 letter wordlist" with 2315 words. That seems rather small to me. Using the SOWPODS dictionary (or something very close to it) that I have on my local system, I find:

```bash
% word '.*' | wc -l
267751
% word '.....' | wc -l
12478
```

I don't know if the Wordle authors have announced what wordlist they use, but mine is apparently about 5x as large as Laurent Lessard's. (`word` is a small script on my system that basically just wraps `egrep ^$1$`).

Exploring further with my larger wordlist:

```
% word '.....' | histogram
6441 e
6427 s
5738 a
4248 o
4027 r
3595 i
3269 l
3206 t
2854 n
2399 u
2364 d
1992 y
1947 c
1945 p
1908 m
1682 h
1576 g
1547 b
1426 k
1071 f
1013 w
661 v
412 z
270 j
268 x
104 q
```

This probably suggests AROSE as a good starting point.  But it seems probable that also considering digrams among 5-letter words might affect the optimal strategy.

**Comment by LaurentLessard** [comment]
Yes, this 2315-word list is the one used by Wordle. You can actually extract it directly from the source code of the Wordle app. For a detailed explanation, check out https://bert.org/2021/11/24/the-best-starting-word-in-wordle/

I updated the readme to add a pointer to this blog post.

**Comment by DavidMertz** [comment]
I'm sad to read that the game is so deterministic with a predefined answer
list, in a fixed order. I hadn't thought about the implementation in the
three days I played. This gives me an algorithm to always guess in one play.

I *do* think that for either this actual game, or some generalization to
more words and true shuffling, probably has a more optimal solution that
takes account of digrams.

I doubt very much it can guarantee 4 plays. But it might reduce the mean
slightly. But I have not proved that, it's just my hunch.
